### ISSUE TITLE
Grid gutterWidth nuances with nested content

### ISSUE THREAD

**Issue by netarc** [dowjones/react-cellblock#10]
Hello, thanks for this useful tool. I feel like either there are some nuances with `gutterWidth` and Columns at-least when it comes to nested grid content or maybe im using it incorrectly and would like some input if you don't mind.

With a Grid and simple two columns:
```JS
<Grid gutterWidth={50}>
  <Row>
    <Column width="4/10">
      Column 1
    </Column>
    <Column width="6/10">
      Column 2
    </Column>
  </Row>
</Grid>
```
I correctly see `gutterWidth` represented in each columns padding:
![image](https://cloud.githubusercontent.com/assets/2561/16711725/d668a4e2-461f-11e6-84b8-c096a0e8fd15.png)

When you nest another row inside a parent column however, the row consumes the gutter of its parent only to reproduce it in its children columns:
```JS
<Grid gutterWidth={50}>
  <Row>
    <Column width="4/10">
      <Row>
        <Column width="5/10">
          Column 1A
        </Column>
        <Column width="5/10">
          Column 1B
        </Column>
      </Row>
    </Column>
    <Column width="6/10">
      Column 2
    </Column>
  </Row>
</Grid>
```
![image](https://cloud.githubusercontent.com/assets/2561/16711737/55be2aa0-4620-11e6-9e59-5ab3faa02995.png)

Where this becomes a problem is if one was wanting to have a specific gutter sizes on the outer level vs the inner level of columns. In my case I was wanting spacing on the first two columns but not the inner columns.

In experimentation if I try to nest another `Grid` to specify no gutter and contain the inner columns it seems to override (all?) and set no gutter anywhere:
```JS
<Grid gutterWidth={50}>
  <Row>
    <Column width="4/10">
      <Grid gutterWidth={0}>
        <Row>
          <Column width="5/10">
            Column 1a
          </Column>
          <Column width="5/10">
            Column 1b
          </Column>
        </Row>
      </Grid>
    </Column>
    <Column width="6/10">
      Column 2
    </Column>
  </Row>
</Grid>
```
![image](https://cloud.githubusercontent.com/assets/2561/16711739/c9685214-4620-11e6-8357-d8de9b281b66.png)

The alternative I found was to ignore `gutterWidth` all-together and just set it to 0 and use a `offset` on the 2nd outer column:
```JS
<Grid gutterWidth={0}>
  <Row>
    <Column width="4/10">
      <Row>
        <Column width="5/10">
          Column 1a
        </Column>
        <Column width="5/10">
          Column 1b
        </Column>
      </Row>
    </Column>
    <Column width="5/10" offset="1/10">
      Column 2
    </Column>
  </Row>
</Grid>
```
![image](https://cloud.githubusercontent.com/assets/2561/16711758/8b1572b6-4621-11e6-9a2e-16b5eb8fda16.png)

This doesn't seem terribly clean if one wants to have more than a couple nested columns though.. Am I expecting too much from `gutterWidth` for nested content?

**Comment by skiano** [comment]
It's not really designed to put Grids inside of one another, and typically with grids, the gutters are consistent. If you want to have some areas without gutters or with different ones you may be able to add css to your page to do it. It would be a bit strange and you would need to use `!important` but I think it would work, because gutters are just made by padding inside the columns.

**Comment by netarc** [comment]
Thanks for the response and suggestion!
