### ISSUE TITLE
Getting items to stack. 

### ISSUE THREAD

**Issue by octalmage** [dowjones/react-cellblock#11]
I'm having a difficult time getting some items to stack. Lets say I have a 1/4, 1/4, and a 1/2 cell. Is there a way to get them all to stack when we get to a certain breakpoint? I also tried with a two 1/2 cells also, but I believe since they're fractions you'll have use the observe grid? 

Thanks!

**Comment by skiano** [comment]
Yes, as long as they are fractions they will continue to shrink, unless you use observe grid and change the width value. In an old version, there was also support for using absolute units (which would behave more how you were expecting), but I felt the combination became more confusing then helpful.
