### ISSUE TITLE
Allow multiple grids to have different gutters

### ISSUE THREAD

**Issue by skiano** [dowjones/react-cellblock#15]
There is a pending pull request about this:

See https://github.com/dowjones/react-cellblock/pull/12 for discussion

**Comment by skiano** [comment]
this is now available in `react-cellblock@3.0.0`

**Comment by hooddanielc** [comment]
🍰 well done

**Comment by skiano** [comment]
@hooddanielc Out of curiosity, what are you using this for?

**Comment by hooddanielc** [comment]
I plan on using it for a site I'm working on called haven of code. I want it to be a easy to use publishing platform that offers an extendable layout engine, tooling for pushing and scaling to amazon web services, extendable API, customizable front end, all geared toward generating a community of people who want to learn and teach anything they want. I've been pushing all that work to https://github.com/hooddanielc/new-havenofcode . The current site looks like a GitHub ripoff. It's not intended to be only computer programming content.

It's going to be a long time before it gets off the ground at all. I'm hoping within next 6 months

**Comment by hooddanielc** [comment]
Also I've heard from some designers that they've had a lot of trouble getting some designs implemented simply because the grid system an entire site was built on was not the same as the design. This project appears to be a great solution for that.

**Comment by skiano** [comment]
Cool! Let me know when it's up :)
