### ISSUE TITLE
PeerDependencies in Package.json

### ISSUE THREAD

**Issue by DavidDaCosta** [dowjones/react-cellblock#20]
Shouldn't React Libraries be Peer-dependencies?  I then think this is better so the library is not tied to a specific version...

**Comment by skiano** [comment]
I think you are correct, yes

**Comment by mrchief** [comment]
Does cellblock work with React 15? I remember 15 causing problems. If that is no longer an issue, we can open it up as a peer dependency.

**Comment by skiano** [comment]
@mrchief the latest release has updates for all the dependencies. Checkout https://github.com/dowjones/react-cellblock/pull/16
