### ISSUE TITLE
rows have max-width

### ISSUE THREAD

**Issue by RezaRahmati** [dowjones/react-cellblock#8]
Hi

I am new to cellblock
I have used that like this

```
 <Grid>
        <Row>
          <Column width="6/10">
            <LiveStream
              hasLarge={true}
              collection={list}
              />
          </Column>
          <Column width="4/10">
            <BarChart data={chartData} options={chartOptions}/>
          </Column>
        </Row>
</Grid>
```

the problem is the row has max-width style (see attachment)
Someone else also reported the same issue, but I really didn't get the answer :(

![3](https://cloud.githubusercontent.com/assets/10086092/16080726/26da68c6-32d8-11e6-9893-79e78e382443.png)

**Comment by skiano** [comment]
Relates to: https://github.com/dowjones/react-cellblock/issues/6
